var number = [78, 65, 358, 254, 22];
number.push(63);
// console.log(number);
var friends = ['balam', 'kalam', 'salam'];
console.log(friends);
friends.push('gelam');
friends.push('jalam');
// friends.pop();
// console.log(friends);
var element = friends.pop();
console.log(element);